name: Android CI

on:
  push:
    branches: [ "neko11-stable", "neko11-dev" ]
  pull_request:
    branches: [ "neko11-stable", "neko11-dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Build Neko11 with Gradle
      run: ./gradlew assembleDebug
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
         name: neko11-DEV-artifact
         path: app/build/outputs/apk/debug/app-debug.apk

